f1 = input("Enter the Fruit Number 1: ")
f2 = input("Enter the Fruit Number 2: ")
f3 = input("Enter the Fruit Number 3: ")
f4 = input("Enter the Fruit Number 4: ")
f5 = input("Enter the Fruit Number 5: ")
f6 = input("Enter the Fruit Number 6: ")
f7 = input("Enter the Fruit Number 7: ")
print("Given Fruit List:")
myfruit = [f1,f2,f3,f4,f5,f6,f7]
print(myfruit)